source/fundamentals/connection/connection-options.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36984
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36984-connection-options/fundamentals/connection/connection-options/
=> DOCSP-36984 Connection Options

source/faq.txt, source/fundamentals.txt, source/index.txt, source/previous-versions.txt, source/quick-start.txt, source/tools.txt, source/troubleshooting.txt, source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37014
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37014-index/
=> DOCSP-37014 - Index

source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37016> and <https://jira.mongodb.org/browse/DOCSP-37017>
Staging:
- https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37017-whats-new/whats-new/
- https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37017-whats-new/upgrade/
=> DOCSP-37016/37017 - What's New and Upgrade

source/troubleshooting.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37015
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37015-troubleshooting/troubleshooting/
=> DOCSP-37015 - Troubleshooting

source/fundamentals/connection/network-compression.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36985
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36985-network-compression/fundamentals/connection/network-compression/
=> DOCSP-36985 network compression

source/fundamentals.txt, source/fundamentals/type-hints.txt, source/tools.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37006
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37006-type-hints/fundamentals/type-hints/
=> DOCSP-37006 - Type Hints

source/faq.txt, source/fundamentals.txt, source/fundamentals/periodic-executors.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37005
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37005-periodic-executors/fundamentals/periodic-executors/
=> DOCSP-37005 - Periodic Executors

source/fundamentals/connection/server-selection.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36986
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36986-server-selection/fundamentals/connection/server-selection/
=> server selection updates

source/fundamentals.txt, source/fundamentals/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37004
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37004-indexes/fundamentals/indexes/
=> DOCSP-37004 - Indexes

source/fundamentals/connection/tls.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36987
Staging -https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36987-tls/fundamentals/connection/tls/#std-label-OCSP
=> DOCSP-36987 TLS/SSL

source/fundamentals/crud/count.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36989
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36989-count/fundamentals/crud/count/
=> DOCSP-36989 Count

source/fundamentals/crud/bulk-write.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36988
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36988-bulk-write/fundamentals/crud/bulk-write/
=> DOCSP-36988 Bulk Write

source/fundamentals.txt, source/fundamentals/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37001
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37001-enterprise-auth/fundamentals/enterprise-authentication/
=> DOCSP-37001 - Enterprise Auth

source/fundamentals.txt, source/fundamentals/gridfs.txt, source/fundamentals/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37002
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37002-gridfs/fundamentals/gridfs/
=> DOCSP-37002 - GridFS

source/fundamentals/crud/cursors.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36990
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36990-cursors/fundamentals/crud/cursors/
=> DOCSP-36990 cursors

source/fundamentals.txt, source/fundamentals/authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36996
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36996-auth/fundamentals/authentication/
=> DOCSP-36996 - Authentication

source/fundamentals/crud/find.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36991
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36991-find/fundamentals/crud/find/
=> DOCSP-36991 Find

source/fundamentals/crud/insert.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36992
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36992-insert/fundamentals/crud/insert/
=> DOCSP-36992 Insert

source/fundamentals.txt, source/fundamentals/csot.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36998
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36998-csot/fundamentals/csot/
=> DOCSP-36998 - CSOT

source/fundamentals.txt, source/fundamentals/collations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36997
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36997-collation/fundamentals/collations/
=> DOCSP-36997 - Collation

source/fundamentals.txt, source/fundamentals/aggregation.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36995
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36995-aggregation/fundamentals/aggregation/
=> DOCSP-36995 - Aggregation

source/fundamentals/data-formats/custom-types.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-36993
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-36993-custom-types/fundamentals/data-formats/custom-types/
=> DOCSP-36993 Custom types

source/fundamentals/connection/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36983>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/pymongo/docsworker-xlarge/DOCSP-36983/fundamentals/connection/connect/>
=> fundamentals > connection > connect.txt

source/previous-versions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37328
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37328-prev-versions/previous-versions/
=> DOCSP-37328 - Previous Versions

source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37363
Staging:
- [What's New](https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36146-whats-new/whats-new/)
- [Breaking Changes](https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-36146-whats-new/upgrade/#std-label-version-4.7-breaking-changes)
=> DOCSP-37363 - What's New

source/index.txt, source/issues-and-help.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37498
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37498-issues/issues-and-help/
=> DOCSP-37498 - Issues and Help

source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37502
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37502-upgrade/upgrade/
=> DOCSP-37502 - Upgrade

snooty.toml, source/index.txt, source/write-operations.txt, source/write/insert.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37534
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37534-write-insert/write/insert/
=> DOCSP-37534 Insert

source/fundamentals.txt, source/index.txt, source/security.txt, source/security/in-use-encryption.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37521
Staging - https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/
=> DOCSP-37521 - In-Use Encryption

source/connect/stable-api.txt, source/includes/connect/stable_api.py, source/includes/troubleshooting/stable-api.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-37508
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37508-stable-api/connect/stable-api/
=> DOCSP-37508 - Stable API

source/includes/read/distinct.py, source/read.txt, source/read/distinct.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37554
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37554-distinct/read/distinct/
=> DOCSP-37554 Retrieve Distinct Values

source/aggregation-tutorials/filtered-subset.txt, source/aggregation.txt, source/connect.txt, source/fundamentals.txt, source/troubleshooting.txt
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/fix-build-errors/
=> Fix build errors

source/tools.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37500
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37500-tools/tools/
=> DOCSP-37500 - Tools

snooty.toml, source/includes/usage-examples/sample-app-intro.rst, source/includes/usage-examples/sample-app.py, source/includes/usage-examples/starter-app.py, source/security.txt, source/security/authentication.txt, source/security/enterprise-authentication.txt
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/auth-examples/security/
=> Authentication

source/includes/read/specify-documents-to-return.py, source/read.txt, source/read/specify-documents-to-return.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37540
https://jira.mongodb.org/browse/DOCSP-37541
https://jira.mongodb.org/browse/DOCSP-37549
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37540-limit/read/specify-documents-to-return/
=> DOCSP-37540/1/9 Limit, Sort, Skip

source/includes/read/distinct.py, source/includes/write/bulk-write.py, source/includes/write/delete.py, source/read/distinct.txt, source/write/bulk-write.txt
JIRA - 
https://jira.mongodb.org/browse/DOCSP-38490
https://jira.mongodb.org/browse/DOCSP-38491
https://jira.mongodb.org/browse/DOCSP-38494
Staging - 
[Delete](https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/code-example-generation/write/delete/)
[Bulk Write](https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/code-example-generation/write/bulk-write/)
[Distinct](https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/code-example-generation/read/distinct/)
=> Read and Write Code Examples

source/includes/indexes/indexes.py, source/indexes/clustered-index.txt, source/indexes/compound-index.txt, source/indexes/geospatial-index.txt, source/indexes/multikey-index.txt, source/indexes/single-field-index.txt, source/indexes/unique-index.txt, source/work-with-indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38493
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-38493-index-code-examples/indexes/clustered-index/
=> DOCSP-38493 Index Code Examples

source/aggregation/aggregation-tutorials/filtered-subset.txt, source/aggregation/aggregation-tutorials/group-total.txt, source/aggregation/aggregation-tutorials/multi-field-join.txt, source/aggregation/aggregation-tutorials/one-to-one-join.txt, source/aggregation/aggregation-tutorials/unpack-arrays.txt, source/includes/aggregation/filtered-subset.py, source/includes/aggregation/group-total.py, source/includes/aggregation/multi-field-join.py, source/includes/aggregation/one-to-one-join.py, source/includes/aggregation/template-app.py, source/includes/aggregation/unpack-arrays.py
JIRA - https://jira.mongodb.org/browse/DOCSP-38492
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-38492/aggregation/aggregation-tutorials/
=> DOCSP-38492 - Aggregation Code Examples

source/fundamentals/data-formats/custom-types.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37515>
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-37515-custom-types/fundamentals/data-formats/custom-types/
=> DOCSP-37515 - Custom Types

source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37493
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37493-landing-page/
=> DOCSP-37493 Update Landing Page

source/includes/authentication/azure-envs-mongoclient.py, source/includes/authentication/azure-imds-connection-string.py, source/includes/authentication/gcp-imds-connection-string.py, source/includes/authentication/gcp-imds-mongoclient.py, source/security/enterprise-authentication.txt
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/oidc-fixes/security/enterprise-authentication/#mongodb-oidc
=> OIDC fixes

source/compatibility.txt
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/4.7-compat/compatibility/
=> Change to sharedinclude

source/write/gridfs.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39456
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-39456-delete-code/write/gridfs/#delete-files
=> DOCSP-39456 - Delete code fix

source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40300
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-40300-connect-link/
=> DOCSP-40300 - Add link to Connect section

source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39884
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-39884-gcp-vm/security/enterprise-authentication/#gcp-imds
=> DOCSP-39884 - Google Compute Engine

source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40566
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-40566-oidc-async/security/enterprise-authentication/#mongodb-oidc
=> DOCSP-40566 - Sync OIDC

source/faq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42913
Staging - https://preview-mongodbmongokart.gatsbyjs.io/pymongo/docsp-42913-broken-link/faq/#how-does-connection-pooling-work-in-pymongo-
=> DOCSP-42913 - Broken link

config/redirects
mut-redirects output:
```
Redirect 301 /docs/languages/python/drivers/pymongo-driver/ https://www.mongodb.com/docs/languages/python/drivers/pymongo-driver/current/
Redirect 301 /docs/languages/python/drivers/pymongo-driver/stable https://www.mongodb.com/docs/languages/python/drivers/pymongo-driver/current/
Redirect 301 /docs/languages/python/drivers/pymongo-driver/master https://www.mongodb.com/docs/languages/python/drivers/pymongo-driver/upcoming/
```
JIRA - N/A
Staging - https://deploy-preview-108--docs-pymongo.netlify.app/
=> Fix Redirects

source/tools.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37736>
Staging - <https://deploy-preview-122--docs-pymongo.netlify.app/tools/#other-tools>
=> DOCSP-37736: Adding FastAPI App Generator to Tools page

source/aggregation.txt, source/aggregation/aggregation-tutorials.txt, source/connect.txt, source/data-formats.txt, source/get-started.txt, source/index.txt, source/indexes.txt, source/indexes/single-field-index.txt, source/read.txt, source/security.txt, source/work-with-indexes.txt, source/write-operations.txt
* DOCSP-44948 TOC Relabel
* final changes
* 2 line edit :(
* suggestions
* linking format
* edit vector search
(cherry picked from commit e8c1a4189e97dbdd9bcf99f7157b6f2726f9ea79)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
=> [Backport V4.8] Shorten TOC

source/aggregation.txt, source/aggregation/aggregation-tutorials.txt, source/connect.txt, source/data-formats.txt, source/get-started.txt, source/index.txt, source/indexes.txt, source/indexes/single-field-index.txt, source/read.txt, source/security.txt, source/work-with-indexes.txt, source/write-operations.txt
* DOCSP-44948 TOC Relabel
* final changes
* 2 line edit :(
* suggestions
* linking format
* edit vector search
(cherry picked from commit e8c1a4189e97dbdd9bcf99f7157b6f2726f9ea79)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
=> [Backport v4.7] DOCSP-44948 TOC Relabel (#127)

config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-46463
Staging -
=> DOCSP-46463 Temporary Redirect for broken link

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-46849
https://deploy-preview-160--docs-pymongo.netlify.app/
=> Add django banner to landing page

config/redirects
Redirects:
```
Redirect 301 /docs/languages/python/pymongo-driver/v4.0/faq/#is-pymongo-fork-safe- https://www.mongodb.com/docs/languages/python/pymongo-driver/v4.0/troubleshooting/#forking-a-process-causes-a-deadlock
Redirect 301 /docs/languages/python/pymongo-driver/v4.1/faq/#is-pymongo-fork-safe- https://www.mongodb.com/docs/languages/python/pymongo-driver/v4.1/troubleshooting/#forking-a-process-causes-a-deadlock
Redirect 301 /docs/languages/python/pymongo-driver/v4.2/faq/#is-pymongo-fork-safe- https://www.mongodb.com/docs/languages/python/pymongo-driver/v4.2/troubleshooting/#forking-a-process-causes-a-deadlock
Redirect 301 /docs/languages/python/pymongo-driver/v4.3/faq/#is-pymongo-fork-safe- https://www.mongodb.com/docs/languages/python/pymongo-driver/v4.3/troubleshooting/#forking-a-pro …
```
=> DOCSP-47880 - FAQ redirect

source/read/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48206>
<li><a href=https://deploy-preview-205--docs-pymongo.netlify.app/read/retrieve>read/retrieve</a></li>
=> DOCSP-48206: Comment page 404

source/includes/troubleshooting/connection-targets.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-48220
pymongo.netlify.app/connect/connection-targets/#autoreconnect
=> DOCSP-48220 - Fix 404

source/tools.txt, source/write/bulk-write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48306>
<li><a href=https://deploy-preview-212--docs-pymongo.netlify.app/tools>tools</a></li><li><a href=https://deploy-preview-212--docs-pymongo.netlify.app/write/bulk-write>write/bulk-write</a></li>
=> DOCSP-48306 - Fix type hints

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48299>
=> DOCSP-48299: Update snooty title

source/serialization.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48328>
<li><a href=https://deploy-preview-220--docs-pymongo.netlify.app/serialization>serialization</a></li>
=> DOCSP-48328: Serialization page feedback

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48974>
<li><a href=https://deploy-preview-242--docs-pymongo.netlify.app/index>index</a></li>
=> DOCSP-48974 - Add CRUD to TOC

.github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48938>
=> DOCSP-48938: Add PR checklist item for checking page titles

source/connect/connection-targets.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48762
<li><a href=https://deploy-preview-253--docs-pymongo.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
=> DOCSP-48762 Add docker note

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-49136>
=> DOCSP-49136 - Fix redirects

snooty.toml, source/reference.txt
=> Backport 264 to v4.12

snooty.toml, source/integrations.txt, source/integrations/flask-celery-integration.txt
=> [Docs+] Build a Newsletter Platform With Flask and MongoDB (#267)

source/data-formats/custom-types/type-codecs.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50734
<li><a href=https://deploy-preview-279--docs-pymongo.netlify.app/data-formats/custom-types/type-codecs>data-formats/custom-types/type-codecs</a></li>
=> DOCSP-50734 Lengthen name of Type Codecs page

source/security/authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50729>
<li><a href=https://deploy-preview-280--docs-pymongo.netlify.app/security/authentication>security/authentication</a></li>
=> DOCSP-50729-remove-duplicate-metadata
