- source/includes/read/change-streams.py
- source/includes/usage-examples/retrieve-code-examples.py
- source/read.txt
- source/read/change-streams.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37539
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-37539-change-streams/read/change-streams/
> DOCSP-37539 Change Streams

- source/includes/authentication/auth-properties-commas.rst
- source/security/authentication.txt
- source/security/enterprise-authentication.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40004>
Staging - <https://preview-mongodbshuangela.gatsbyjs.io/pymongo/DOCSP-40004-add-comma-directive-auth-properties/>
> DOCSP-40004 added comma guidance and removed percent encoding guidance

- source/get-started.txt
- source/get-started/connect-to-mongodb.txt
- source/get-started/create-a-connection-string.txt
- source/get-started/create-a-deployment.txt
- source/get-started/download-and-install.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-41595
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-41595-remove-next-buttons/get-started/
> DOCSP-41595 Remove next buttons from get started

- source/connect.txt
- source/connect/csot.txt
- source/connect/network-compression.txt
- source/connect/server-selection.txt
- source/connect/stable-api.txt
- source/includes/connect/ca-file-tabs.rst
- source/includes/connect/client-cert-tabs.rst
- source/includes/connect/compression-tabs.rst
- source/includes/connect/crl-tabs.rst
- source/includes/connect/disable-cert-validation-tabs.rst
- source/includes/connect/disable-host-verification-tabs.rst
- source/includes/connect/insecure-tls-tabs.rst
- source/includes/connect/key-file-password.rst
- source/includes/connect/ocsp-tabs.rst
- source/includes/connect/tls-tabs.rst
- source/security.txt
- source/security/authentication.txt
- source/security/enterprise-authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42384
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/pymongo/DOCSP-42303-update-placeholders/
> DOCSP-42303 Update username and password placeholders

- source/get-started/download-and-install.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43238
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/pymongo/DOCSP-43238-add-windows/get-started/download-and-install/
> DOCSP-43238: Add Windows installation instructions

- source/includes/write/transaction.py
- source/write-operations.txt
- source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41761>
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/pymongo/docsp-41761-addTransactionPage/write/transactions/>
> DOCSP-41761 Add transaction page

- source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43712>
Staging - <https://deploy-preview-107--docs-pymongo.netlify.app/upgrade/>
> DOCSP-43712: Update link to migration guide

- source/get-started/download-and-install.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41642>
Staging - <https://deploy-preview-114--docs-pymongo.netlify.app/get-started/download-and-install/>
> DOCSP-41642:  Add in the in-depth installation instructions

- .github/workflows/vale-tdbx.yml
- source/data-formats.txt
- source/data-formats/time-series.txt
DOCSP-37513
JIRA - <https://jira.mongodb.org/browse/DOCSP-37513>
Staging - <https://deploy-preview-112--docs-pymongo.netlify.app/data-formats/time-series/>
> DOCSP-37513: Time Series Collections

- source/includes/indexes/indexes.py
- source/indexes/atlas-search-index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44135>
Staging - <https://deploy-preview-116--docs-pymongo.netlify.app/indexes/atlas-search-index/>
> DOCSP-44135: Mention vector search in pymongo search indexes page

- source/includes/troubleshooting/tls.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-43384>
Staging - <https://deploy-preview-115--docs-pymongo.netlify.app/troubleshooting/#unsafe-legacy-renegotiation-disabled>
> DOCSP-43384: Troubleshooting openssl legacy unsafe renegotiation

- source/includes/run-command.py
- source/index.txt
- source/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37565>
Staging - <https://deploy-preview-118--docs-pymongo.netlify.app/run-command/>
> DOCSP-37565: Run Command

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44317>
Staging - <https://deploy-preview-121--docs-pymongo.netlify.app/whats-new/>
> DOCSP-44317: Adding Support for Free-threaded Python

- source/aggregation.txt
- source/aggregation/aggregation-tutorials.txt
- source/connect.txt
- source/data-formats.txt
- source/get-started.txt
- source/index.txt
- source/indexes.txt
- source/indexes/single-field-index.txt
- source/read.txt
- source/security.txt
- source/work-with-indexes.txt
- source/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44948>
Staging - <https://deploy-preview-127--docs-pymongo.netlify.app/>
> DOCSP-44948 TOC Relabel

- source/write/bulk-write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45737>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> DOCSP-45737: Clarify that users must specify id for bulk inserted docs

- source/write/bulk-write.txt
From Steve: "The _id doesn't have to be included in general, it is used for illustrative purposes in some of the examples.  The only constraint is that the _ids are unique.  If they're not provided by the client, they will be provided by the server."
JIRA - <https://jira.mongodb.org/browse/DOCSP-45737>
Staging - <https://deploy-preview-134--docs-pymongo.netlify.app/write/bulk-write/>
> Undo DOCSP-45737

- source/write/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45883
Staging - https://deploy-preview-135--docs-pymongo.netlify.app/write/transactions/#example
> DOCSP-45883 - Parallelism in transactions

- snooty.toml
- source/includes/authentication/azure-envs-mongoclient.py
- source/includes/authentication/azure-imds-connection-string.py
- source/includes/authentication/azure-imds-mongoclient.py
- source/includes/authentication/gcp-gke-mongoclient.py
- source/includes/authentication/gcp-imds-connection-string.py
- source/includes/authentication/gcp-imds-mongoclient.py
- source/includes/authentication/percent-encoding.rst
- source/security.txt
- source/security/authentication.txt
- source/security/authentication/aws-iam.txt
- source/security/authentication/kerberos.txt
- source/security/authentication/ldap.txt
- source/security/authentication/oidc.txt
- source/security/authentication/scram.txt
- source/security/authentication/x509.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46651
Staging - https://deploy-preview-148--docs-pymongo.netlify.app/security/authentication/
> DOCSP-46651 - Authentication reorganization

- source/data-formats.txt
- source/data-formats/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46685>
- <https://deploy-preview-159--docs-pymongo.netlify.app/data-formats/>
- <https://deploy-preview-159--docs-pymongo.netlify.app/data-formats/bson/>
> DOCSP-46685: BSON

- source/index.txt
- source/logging.txt
Largely adapted from [this page on the readthedocs domain](https://pymongo.readthedocs.io/en/stable/examples/logging.html).
JIRA - <https://jira.mongodb.org/browse/DOCSP-46696>
<li><a href=https://deploy-preview-154--docs-pymongo.netlify.app/logging>logging</a></li><li><a href=https://deploy-preview-154--docs-pymongo.netlify.app/index>index</a></li>
> DOCSP-46696: Logging page

- source/databases-collections.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46688>
<li><a href=https://deploy-preview-161--docs-pymongo.netlify.app/databases-collections>databases-collections</a></li>
> DOCSP-46688: Add collection configuration sections

- source/connect/connection-options.txt
- source/databases-collections.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46699> and <https://jira.mongodb.org/browse/DOCSP-46700>
<li><a href=https://deploy-preview-165--docs-pymongo.netlify.app/connect/connection-options>connect/connection-options</a></li><li><a href=https://deploy-preview-165--docs-pymongo.netlify.app/databases-collections>databases-collections</a></li>
> DOCSP-46699: Retryable reads and writes

- source/includes/monitoring/monitoring.py
- source/index.txt
- source/monitoring.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46689> and  <https://jira.mongodb.org/browse/DOCSP-46702>
<li><a href=https://deploy-preview-166--docs-pymongo.netlify.app/monitoring>monitoring</a></li><li><a href=https://deploy-preview-166--docs-pymongo.netlify.app/index>index</a></li>
> DOCSP-46689: Monitoring

- source/data-formats.txt
- source/data-formats/extended-json.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46694
<li><a href=https://deploy-preview-169--docs-pymongo.netlify.app/data-formats/extended-json>data-formats/extended-json</a></li><li><a href=https://deploy-preview-169--docs-pymongo.netlify.app/data-formats>data-formats</a></li>
> DOCSP-46694 - Extended JSON

- source/data-formats/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47282>
<li><a href=https://deploy-preview-176--docs-pymongo.netlify.app/data-formats/bson>data-formats/bson</a></li>
> DOCSP-47282: RawBSONDocument information

- source/includes/authentication/kubernetes-connection-string.py
- source/includes/authentication/kubernetes-mongoclient.py
- source/security/authentication/oidc.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42014>
<li><a href=https://deploy-preview-184--docs-pymongo.netlify.app/security/authentication/oidc>security/authentication/oidc</a></li>
> DOCSP-42014: Add OIDC Kubernetes support

- source/includes/write/bulk-write.py
- source/write/bulk-write.txt
- source/write/transactions.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43420
<li><a href=https://deploy-preview-177--docs-pymongo.netlify.app/write/bulk-write>write/bulk-write</a></li><li><a href=https://deploy-preview-177--docs-pymongo.netlify.app/write/transactions>write/transactions</a></li>
> DOCSP-43420: Client bulk write

- source/write/transactions.txt
Poached from [Nora's PR](https://github.com/mongodb/docs-java/pull/623) with a couple of method name tweaks.
JIRA - <https://jira.mongodb.org/browse/DOCSP-46686>
<li><a href=https://deploy-preview-188--docs-pymongo.netlify.app/write/transactions>write/transactions</a></li>
> DOCSP-46686: Causal consistency

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46697>
<li><a href=https://deploy-preview-186--docs-pymongo.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
> DOCSP-46697: SRV record section

- config/redirects
`Redirect 301 /docs/languages/python/pymongo-driver/compatibility/ https://www.mongodb.com/docs/languages/python/pymongo-driver/current/compatibility/`
JIRA - <https://jira.mongodb.org/browse/DOCSP-48048>
> DOCSP-48048 - Compat redirect

- .vscode/settings.json
- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
<li><a href=https://deploy-preview-198--docs-pymongo.netlify.app/index>index</a></li><li><a href=https://deploy-preview-198--docs-pymongo.netlify.app/read>read</a></li>
> [PyMongo] Remove "MongoDB" from page title

- source/connect/mongoclient.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46879>
<li><a href=https://deploy-preview-199--docs-pymongo.netlify.app/connect/mongoclient>connect/mongoclient</a></li><li><a href=https://deploy-preview-199--docs-pymongo.netlify.app/index>index</a></li>
> DOCSP-46879: Add reference + link to MongoClient keyword arguments

- source/data-formats/bson.txt
- source/data-formats/custom-types.txt
- source/data-formats/dates-and-times.txt
- source/data-formats/time-series.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48166>
<li><a href=https://deploy-preview-213--docs-pymongo.netlify.app/data-formats/bson>data-formats/bson</a></li><li><a href=https://deploy-preview-213--docs-pymongo.netlify.app/data-formats/custom-types>data-formats/custom-types</a></li><li><a href=https://deploy-preview-213--docs-pymongo.netlify.app/data-formats/dates-and-times>data-formats/dates-and-times</a></li><li><a href=https://deploy-preview-213--docs-pymongo.netlify.app/data-formats/time-series>data-formats/time-series</a></li>
> DOCSP-48166: Add async examples for Data Formats pages

- source/logging.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48327>
<li><a href=https://deploy-preview-219--docs-pymongo.netlify.app/logging>logging</a></li>
> DOCSP-48327: Address technical feedback on Logging page

- config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCS-16978>
> DOCS-16978 - fix 404s

- source/includes/indexes/indexes-async.py
- source/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48164>
<li><a href=https://deploy-preview-235--docs-pymongo.netlify.app/indexes>indexes</a></li>
> DOCSP-48164: Async examples for Indexes page

- source/connect.txt
- source/connect/connection-options.txt
- source/connect/connection-options/connection-pools.txt
- source/connect/connection-options/network-compression.txt
- source/connect/connection-options/server-selection.txt
- source/connect/connection-options/stable-api.txt
- source/connect/connection-targets.txt
- source/connect/mongoclient.txt
- source/data-formats/extended-json.txt
- source/includes/connect/atlas-connection-async.py
- source/includes/connect/compression-tabs.rst
- source/includes/usage-examples/connect-sample-app-async.py
JIRA - <https://jira.mongodb.org/browse/DOCSP-48161>
<li><a href=https://deploy-preview-236--docs-pymongo.netlify.app/connect>connect</a></li><li><a href=https://deploy-preview-236--docs-pymongo.netlify.app/connect/connection-options>connect/connection-options</a></li><li><a href=https://deploy-preview-236--docs-pymongo.netlify.app/connect/connection-options/connection-pools>connect/connection-options/connection-pools</a></li><li><a href=https://deploy-preview-236--docs-pymongo.netlify.app/connect/connection-options/network-compression>connect/connection-options/network-compression</a></li><li><a href=https://deploy-preview-236--docs-pymongo.netlify.app/connect/connection-options/server-selection>conne …
> DOCSP-48161: Async examples for Connect pages

- source/includes/authentication/azure-envs-mongoclient-async.py
- source/includes/authentication/azure-imds-connection-string-async.py
- source/includes/authentication/azure-imds-mongoclient-async.py
- source/includes/authentication/gcp-gke-mongoclient-async.py
- source/includes/authentication/gcp-imds-connection-string-async.py
- source/includes/authentication/gcp-imds-mongoclient-async.py
- source/includes/authentication/kubernetes-connection-string.py
- source/includes/authentication/kubernetes-mongoclient.py
- source/includes/connect/ca-file-tabs.rst
- source/includes/connect/client-cert-tabs.rst
- source/includes/connect/crl-tabs.rst
- source/includes/connect/disable-cert-validation-tabs.rst
- source/includes/connect/disable-host-verification-tabs.rst
- source/includes/connect/insecure-tls-tabs.rst
- source/includes/connect/key-file-password.rst
- source/includes/connect/ocsp-tabs.rst
- source/includes/connect/tls-tabs.rst
- source/security.txt
- source/security/authentication/aws-iam.txt
- source/security/authentication/kerberos.txt
- source/security/authentication/ldap.txt
- source/security/authentication/oidc.txt
- source/security/authentication/scram.txt
- source/security/authentication/x509.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48166>
<li><a href=https://deploy-preview-237--docs-pymongo.netlify.app/security>security</a></li><li><a href=https://deploy-preview-237--docs-pymongo.netlify.app/security/authentication/aws-iam>security/authentication/aws-iam</a></li><li><a href=https://deploy-preview-237--docs-pymongo.netlify.app/security/authentication/kerberos>security/authentication/kerberos</a></li><li><a href=https://deploy-preview-237--docs-pymongo.netlify.app/security/authentication/ldap>security/authentication/ldap</a></li><li><a href=https://deploy-preview-237--docs-pymongo.netlify.app/security/authentication/oidc>security/authentication/oidc</a></li><li><a …
> DOCSP-48166: Async examples for Security pages

- source/crud.txt
- source/crud/bulk-write.txt
- source/crud/delete.txt
- source/crud/geo.txt
- source/crud/gridfs.txt
- source/crud/insert.txt
- source/crud/transactions.txt
- source/crud/update.txt
- source/includes/gridfs/gridfs-async.py
- source/includes/usage-examples/write-code-examples-async.py
- source/includes/write/bulk-write-async.py
- source/includes/write/delete-async.py
- source/includes/write/transaction-async.py
- source/includes/write/transaction.py
- source/includes/write/update-async.py
JIRA - <https://jira.mongodb.org/browse/DOCSP-48162>
<li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud>crud</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/bulk-write>crud/bulk-write</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/delete>crud/delete</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/geo>crud/geo</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/gridfs>crud/gridfs</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/insert>crud/insert</a></li><li><a href=https://deploy-preview-239--docs-pymongo.netlify.app/crud/transactions>crud/ …
> DOCSP-48162: Async examples for Write pages

- source/security.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48719>
<li><a href=https://deploy-preview-240--docs-pymongo.netlify.app/security>security</a></li>
> DOCSP-48719: Update non-Mongo credential placeholders

- source/crud.txt
- source/crud/query.txt
- source/integrations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48844>
https://deploy-preview-248--docs-pymongo.netlify.app/integrations/#django
> DOCSP-48844: django copy update

- source/includes/pymongo-async-experimental.rst
- source/reference/migration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49367>
<li><a href=https://deploy-preview-261--docs-pymongo.netlify.app/reference/migration>reference/migration</a></li>
> DOCSP-493767 Update migration admonitions to clarify release phases

- snooty.toml
- source/reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49614>
<li><a href=https://deploy-preview-264--docs-pymongo.netlify.app/reference>reference</a></li>
> References landing page

- snooty.toml
- source/integrations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50383
<li><a href=https://deploy-preview-273--docs-pymongo.netlify.app/integrations>integrations</a></li>
> DOCSP-50383: Add links to preview page

- source/integrations/flask-celery-integration.txt
JIRA 1 - <https://jira.mongodb.org/browse/DOCSP-52054>
JIRA 2 - <https://jira.mongodb.org/browse/DOCSP-52053>
JIRA 3 - <https://jira.mongodb.org/browse/DOCSP-52052>
<li><a href=https://deploy-preview-283--docs-pymongo.netlify.app/integrations/flask-celery-integration>integrations/flask-celery-integration</a></li>
> DOCSP-52054-fix-internal-404s
